on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@v5
      - name: Setup sourcepawn
        uses: https://github.com/rumblefrog/setup-sp@bb7306e551914d48b2d8405dba17ddc46a4a12a2
        with:
          version: '1.12.x'
      - name: Build Plugins
        env:
          SPCOMP_PATH: spcomp
        run: chmod +x compile_all.sh && ./compile_all.sh
      - name: Upload artifacts 
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with: 
          path: plugins/*