on: [push]
jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v3
      - name: Setup sourcepawn
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.12.x'
      - name: Build Plugins
        env:
          SPCOMP_PATH: spcomp
        run: ./compile_all.sh
      - uses: https://data.forgejo.org/actions/upload-artifact@v4
        with: 
          path: plugins/*