#include "accept/FreeRevive.sp"
#include "accept/UltimateSacrifice.sp"

#include "reject/RandomProp.sp"
#include "reject/BecomeDisgruntled.sp"
#include "reject/spin.sp"
#include "reject/CarAlarm.sp"
#include "reject/Explode.sp"
#include "reject/BecomeRandomPeanut.sp"
#include "reject/RockDrop.sp"
#include "reject/Burn.sp"
#include "reject/StealItem.sp"
#include "reject/Spook.sp"
#include "reject/Kill.sp"
#include "reject/Gnome.sp"